### ISSUE TITLE
DM Buttons missing

### ISSUE THREAD

**Issue by jakeg1** [TakosThings/Battlefield#2]
the "create new group dm" as well the "add user to group dm" button are missing from this theme.

**Comment by TakosThings** [comment]
Can't replicate on my end. The screen shots below show the buttons.  Perhaps your window is too narrow which causes the buttons to disappear.
![](https://i.imgur.com/D9QUPzX.png)
![](https://i.imgur.com/z0RnQQq.png)

**Comment by TakosThings** [comment]
I've also just pushed v1.17.1 which will fix the impossible to read text you see in the above screenshots.

**Comment by jakeg1** [comment]
I'm sorry, i should have triple read my post before i posted it. I was actually talking about the button "create group dm" inside "select friends" menu.
![untitled-1](https://cloud.githubusercontent.com/assets/18585912/20660601/3f178342-b596-11e6-9d02-8071d4a84441.png)
At the moment it seems impossible to create or add people to group DMs with this theme.
